### ISSUE TITLE
Image tag 'stable' points to bugged release

### ISSUE THREAD

**Issue by ipatrykx** [k8snetworkplumbingwg/multus-cni#977] opened 2022-11-30 12:51 UTC
Hi all :)

I am currently working with some E2E tests for Network Resource Injector and I've encountered the bug described in #944 

**What happend**:

Got an error while creating a pod:
```
Warning  FailedCreatePodSandBox  3s    kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "78f0ee34808795339a4f7b12303e8885a2c086dcbcb26cf02c94df6ef02a6bf3": Multus: [mysterious/nri-e2e-test/]: error loading k8s delegates k8s args: TryLoadPodDelegates: error in getting k8s network for pod: GetNetworkDelegates: failed getting the delegate: getKubernetesDelegate: failed to get a ResourceClient instance: getKubeletClient: error getting pod resources from client: getPodResources: failed to list pod resources, &{0xc0002cce00}.Get(_) = _, rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial unix unix:/var/lib/kubelet/pod-resources/kubelet.sock: connect: no such file or directory"
```

**What you expected to happen**:

Pod should be created

**How to reproduce it (as minimally and precisely as possible)**:

Clone [Network Resource Injector repository](https://github.com/k8snetworkplumbingwg/network-resources-injector) and run `make e2e`
Although, as the tests are currently a bit broken, you might to have to change `CNIS_DAEMONSET_URL` in `scripts/e2e_setup_cluster.sh` to `https://raw.githubusercontent.com/k8snetworkplumbingwg/multus-cni/v3.9.2/e2e/cni-install.yml` as cni-install.yaml was changed to be a template in Multus repository and that was not updated in NRI e2e tests yet.

**Anything else we need to know?**:

I know the bug was already fixed (encountered the same issue a few days ago with SR-IOV CNI and tested the `latest` image), but the real problem here is (I think) that `stable` image tag still points to broken image. As I believe `stable` might be used quite often, and therefore more people might encounter this issue as well. Just wanted to kindly ask if it is possible to move the tag to some more recent image? If it's not possible, please just close this issue. :)

**Environment**:
Not providing environment details as I believe those are not important here.

**Comment by s1061123** [comment] 2022-11-30 14:21
I'm looking #946, the fix of #944 and `stable` does not have the root cause of the #944, https://github.com/k8snetworkplumbingwg/multus-cni/commit/c6fa047212efc3a410fb73aa83d2594a4f914320.

So it seems to be not the issue, #944, another issue. 

BTW, could you please provide the multus daemonset yaml file to reproduce the issue?

**Comment by s1061123** [comment] 2022-11-30 14:49
I run e2e but I cannot see such errors. Could you please provide how to reproduce that?

```
$ make e2e
(snip)
~ [SLOW TEST:20.445 seconds]
Node selector test
 (snip)
------------------------------
~ Failure [30.326 seconds]
Node selector test
/(snip)/network-resources-injector/test/e2e/nodeselector_test.go:12
  Cluster node available, default namespace
  /(snip)/network-resources-injector/test/e2e/nodeselector_test.go:17
    POD assigned to correct cluster node, node specified with resource name [It]
    /(snip)/network-resources-injector/test/e2e/nodeselector_test.go:40

    Expected
        <*errors.errorString | 0xc0003631b0>: {
            s: "timed out waiting for the condition",
        }
    to be nil

    /(snip)/network-resources-injector/test/e2e/nodeselector_test.go:46
```

**Comment by s1061123** [comment] 2022-11-30 15:01
Currently we don't have not SR-IOV related equipments, so we don't have CI to test that. We are happy that if you/your organization provide CI environment (as github runner), then we could implement CI tests for SR-IOV related....

**Comment by ipatrykx** [comment] 2022-11-30 15:21
Hi Tomo, thank you for your quick response :)

That's good catch - I've used old daemonset from `v.3.9.2` with `stable` image. However changing that did not fix anything.

The daemonset I am using right now is [the default one form the deployments dir](https://github.com/k8snetworkplumbingwg/multus-cni/blob/master/deployments/multus-daemonset.yml)
I have this error when using `stable` tag when resources are requested in pod I think (need to verify if that's only when network resources are requested). After changing the image to `latest` with the same daemonset.yml there is no error anymore. Same after changing the daemonset.yaml and image tag to `v3.9.2`.

As for the error, that test itself will only report `timed out waiting for the condition` as you've encountered. The easiest way to get the real reason of the error is to watch all the pods with `watch -n 0 kubectl get pod -A` while test is running and `kubectl describe` `e2e-test-pods` while they are pending or stuck in container creating state.

I'll try to recreate that error manually to better describe the issue.

**Comment by s1061123** [comment] 2022-12-01 11:34
I checked gchr.io and understood that now `stable` points `v4.0.0-alpha` release, not `v3.9.2`. So that's the root cause. 

@dougbtv could you please fix the container tag?

**Comment by s1061123** [comment] 2022-12-01 15:09
Now `stable` tag points `v3.9.2` again, so it should be fixed, hence let me close this issue.

**Closed by s1061123** 2022-12-01 15:09 UTC
