### ISSUE TITLE
Unique IP address across the cluster

### ISSUE THREAD

**Issue by subrnath** [k8snetworkplumbingwg/multus-cni#52] opened 2018-04-13 07:19 UTC
We are invoking IPVLAN plugin via multus-cni. Each POD is allocated an  unique IP address from the subnet start and end range ( as mentioned in IPAM args). But the uniqueness of the IP is in a host and not across the cluster. /var/lib/cni/networks/<network_id>/last_reserved_ip.0 maintains the last allocated ip for the subnet/network and it's maintained in each host.

It will be good, if multus-cni provides the uniqueness of the IP address across the cluster level.

**Comment by s1061123** [comment] 2018-04-23 05:45
Hi @subrnath

Regarding above comment, you may use 'host-local' plugin for IP Address Management (IPAM) and the issue is related to 'host-local' plugin, not multus-cni.
https://github.com/containernetworking/plugins/tree/master/plugins/ipam/host-local

Multus-cni just invokes CNI plugin (including IPAM) as a meta plugin, so I guess it might be wrong place to discuss about it.
Could you please double check about it?

**Comment by subrnath** [comment] 2018-04-23 20:12
Thanks. Yes, we are using host-local. So with what is the IPAM option to have cluster wise unique IP address? So as i understand, host-local ensures host wise unique IP address.

**Comment by s1061123** [comment] 2018-04-26 13:01
@subrnath just a reminder.

I will close it in someday next week.

**Closed as completed** 2018-04-27 07:19 UTC
