### ISSUE TITLE
Provide arm64 builds for thick packages

### ISSUE THREAD

**Issue by bjencks** [k8snetworkplumbingwg/multus-cni#1225] opened 2024-02-07 00:01 UTC
**What would you like to be added**:

Published *-thick (both snapshot and release) images should have arm64 builds.

**Why is this needed**:

Parity with thin packages, which provide 5 architectures (amd64, arm/v7, arm64, ppc64le, s390x).

**Comment by dougbtv** [comment] 2024-02-29 14:50
Thanks Richard, that is exactly the situation. Let's close it as a dupe of #1136

**Closed by dougbtv** 2024-02-29 14:50 UTC

**Comment by bobz965** [comment] 2024-04-28 09:51
it looks like ghcr.io/fishgrimsby/multus-cni in your yml is only amd64.

**Comment by fishgrimsby** [comment] 2024-04-28 10:00
> it looks like ghcr.io/fishgrimsby/multus-cni in your yml is only amd64.

Can you expand what you mean @bobz965 ? The thick deployment yaml uses:

`image: ghcr.io/fishgrimsby/multus-cni:snapshot-thick` or `image: ghcr.io/fishgrimsby/multus-cni:stable-thick` depending on latest/tagged version, and doesn't define an architecture

You can verify the OS/Arch available on the packages they refer to at: https://github.com/fishgrimsby/multus-cni/pkgs/container/multus-cni/205115737?tag=snapshot-thick or https://github.com/fishgrimsby/multus-cni/pkgs/container/multus-cni/180201655?tag=stable-thick

**Comment by bobz965** [comment] 2024-04-28 10:16
sorry, i got the arm image. 

docker pull --platform=linux/arm64 ghcr.io/fishgrimsby/multus-cni:stable-thick

if not set --platform=linux/arm64, only get the amd64. 

it is not a multi-arch image, it is just one arch.

**Comment by fishgrimsby** [comment] 2024-04-28 10:32
@bobz965 What platform are you running the docker pull command from? If you are running it from an amd64 machine then I would say that is expected behaviour. Docker will select the correct image for the machine you are pulling from.

If I run it from an arm64 machine, I get the arm64 image without having to specify the platform. If I run it from an amd64 machine, I get the amd64 image.

Are you saying that when you run `docker pull ghcr.io/fishgrimsby/multus-cni:stable-thick` from an arm64 machine you are getting the amd64 image instead of the arm64? I am not experiencing that

**Comment by bobz965** [comment] 2024-04-29 01:33
> @bobz965 What platform are you running the docker pull command from? If you are running it from an amd64 machine then I would say that is expected behaviour. Docker will select the correct image for the machine you are pulling from.
> 
> If I run it from an arm64 machine, I get the arm64 image without having to specify the platform. If I run it from an amd64 machine, I get the amd64 image.
> 
> Are you saying that when you run `docker pull ghcr.io/fishgrimsby/multus-cni:stable-thick` from an arm64 machine you are getting the amd64 image instead of the arm64? I am not experiencing that

yeah, i still do not know, why i get a and64 in my mac arm64 PC. but still thanks for your reply.
